.TH	LPSNAKE 6 "15 outubro 2021" Game "Manual do Usuário linux"
.SH NOME
lpsnake \- Jogo da cobrinha.
.SH SINOPSE
\fBlpsnake\fP [\fI\,NÚMERO_VELOCIDADE_EXECUÇÃO\/\fP] [\fI\,COR_DA_COBRA\/\fP]
.SH DESCRIÇÃO
.PP
Lpsnake é um jogo onde você controla uma cobrinha que come
insetos e cresce, conforme ela cresce voce deve ter cuidado
para não colidir em si próprio ou nas paredes que revestem
o cenário 2D.
.PP
Velocidade de execução não pode ser menor que 2 nem maior que
500.
.PP
Cores disponiveis são vermelho azul amarelo rosa laranja sendo
a cor padrão o verde.
.SH EXEMPLOS
.TP
lpsnake 100 amarelo
.SH DIREITOS AUTORAIS
lpsnake
Copyright bsd tree clause license. 2021 2022.
Puiz Paulo de Lima Araújo.
